id = "catppuccin-transparent"
name = "Catppuccin Transparent"
schema_version = 1
version = "0.2.18.1"
authors = [
    "Catppuccin <releases@catppuccin.dev>",
    "Jeffrey Thor <thorjeffrey@gmail.com>",
]
description = "🦀 Soothing pastel theme for Zed with transparency"
repository = "https://github.com/JeffreyThor/zed-catppuccin-transparent"
